export const quotes = [
    "“We become what we think about” – Earl Nightingale", 
    "“People who are crazy enough to think they can change the world, are the ones who do.”- Rob Siltanen", 
    "“Optimism is the one quality more associated with success and happiness than any other.”- Brian Tracy", 
    "“Happiness is not something readymade. It comes from your own actions.”-Dalai Lama", 
    "“All our dreams can come true if we have the courage to pursue them.”- Walt Disney", 
    "“Success is not final, failure is not fatal: it is the courage to continue that counts.” Winston Churchill",
    "“Believe you can and you’re halfway there.” Theodore Roosevelt",
    "“I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.” – Jimmy Dean",
    "“Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new.”- Brian Tracy",
    "“It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.” – William James",
    "“You are never too old to set another goal or to dream a new dream.” – C.S. Lewis",
    "“We must be willing to let go of the life we planned so as to have the life that is waiting for us.” – Joseph Campbell",
    "“Everything you’ve ever wanted is on the other side of fear.”- George Addair",
    "“You get what you give.” – Jennifer Lopez",
    "“Happiness is not by chance, but by choice.” – Jim Rohn",
    "“Be the change that you wish to see in the world.”- Mahatma Ghandi",
    "“If I cannot do great things, I can do small things in a great way.” – Martin Luther King Jr.",
    "“We generate fears while we sit. We overcome them by action.” –  Dr. Henry Link",
    "“Today’s accomplishments were yesterday’s impossibilities.” – Robert H. Schuller",
    "“Light tomorrow with today!” –  Elizabeth Barrett Browning",
    "“The only limit to our realization of tomorrow will be our doubts of today.” – Franklin D. Roosevelt",
    "“Keep your face always toward the sunshine, and shadows will fall behind you.” – Walt Whitman",
    "“The bad news is time flies. The good news is you’re the pilot.” – Michael Altshuler",
    "“Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination.”  – Mae Jemison",  
    "“Let us make our future now, and let us make our dreams tomorrow’s reality.” –  Malala Yousafzai",
    "“Don’t Let Yesterday Take Up Too Much Of Today.” – Will Rogers",
    "“For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.” – Jack Canfield",
    "“We may encounter many defeats but we must not be defeated.” – Maya Angelou",
    "“You only live once, but if you do it right, once is enough.”― Mae West",
    "“In three words I can sum up everything I’ve learned about life: it goes on.”― Robert Frost",
    "“Life is what happens to us while we are making other plans.”― Allen Saunders",
    "“I may not have gone where I intended to go, but I think I have ended up where I needed to be. ― Douglas Adams",
    "“Life isn’t about finding yourself. Life is about creating yourself.”― George Bernard Shaw",  
    "“Life is like riding a bicycle. To keep your balance, you must keep moving.”― Albert Einstein",
    "“Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.” ― Marie Curie",
    "“You are the sum total of everything you’ve ever seen, heard, eaten, smelled, been told, forgot ― it’s all there. Everything influences each of us, and because of that I try to make sure that my experiences are positive.” ― Maya Angelou",
    "The best way to get started is to quit talking and begin doing.” ― Walt Disney",
    "“Someone is sitting in the shade today because someone planted a tree a long time ago.” – Warren Buffet",
    "“The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.” – Winston Churchill",
    "“You learn more from failure than from success. Don’t let it stop you. Failure builds character.” – Unknown",
    "“If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.” – Steve Jobs",
    "“Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneur.” – Mohnish Pabrai",
    "“The man who has confidence in himself gains the confidence of others.” – Hasidic Proverb",
    "“What you lack in talent can be made up with desire, hustle and giving 110 percent all the time.” – Don Zimmer",
    "“I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.” – Michael Phelps",
    "“The only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle.” – Steve Jobs",
    "“Creativity is intelligence having fun.” – Albert Einstein",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do.” – Johann Wolfgang Von Goethe",
    "“To see what is right and not do is a lack of courage.” – Confucius",
    "“A room without books is like a body without a soul.” – Marcus Tullius Cicero",
    "“You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.” —George Lorimer F",
    "“Go as far as you can see; when you get there, you’ll be able to see further.” —Thomas Carlyle",
    "“Your talent determines what you can do. Your motivation determines how much you’re willing to do. Your attitude determines how well you do it.” —Lou Holtz",
    "“It’s not whether you get knocked down, it’s whether you get back up.” –Vince Lombardi",
    "“Failure will never overtake me if my determination to succeed is strong enough.” – Og Mandino",
    "“Do what you can with all you have, wherever you are.” – Theodore Roosevelt",
    "“You don’t have to be great to start, but you have to start to be great.” – Zig Ziglar",
    "“Folks are usually about as happy as they make up their minds to be.” – Abraham Lincoln",
    "“If you don’t like the road you’re walking, start paving another one.” – Dolly Parton",
    "“The happiness of your life depends on the quality of your thoughts.” – Marcus Aurelius",
    "“Things work out best for those who make the best of how things work out.” – John Wooden",
    "“My mission in life is not merely to survive, but to thrive.” – Maya Angelou",
    "“Every moment is a fresh beginning.” – T.S Eliot",
    "“Never regret anything that made you smile.” – Mark Twain",
    "“There is no substitute for hard work.”  – Thomas Edison",
    "“May your choices reflect your hopes, not your fears.” – Nelson Mandela"
];